name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest # or specify a version like 2.64.0

      - name: Initialize Terraform
        run: |
          cd Terraform/VirtualMachine
          terraform init

      - name: Plan Terraform
        run: |
          cd Terraform/VirtualMachine
          terraform plan

      - name: Apply Terraform
        run: |
          cd Terraform/VirtualMachine
          terraform apply -auto-approve
