name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # Adjust to your Terraform version

      # Authenticate with Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Show Azure account details
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/VirtualMachine

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/VirtualMachine

      # Plan Terraform changes
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform/VirtualMachine
        env:
          TF_VAR_adminpassword: ${{ secrets.TF_VAR_ADMINPASSWORD }}

      # Apply Terraform changes
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform/VirtualMachine
        env:
          TF_VAR_adminpassword: ${{ secrets.TF_VAR_ADMINPASSWORD }}
